version: '3.8'

services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default
    container_name: grafana
    volumes:
      - Grafana-Storage:/var/lib/grafana

volumes:
  Grafana-Storage:
    name: Grafana-Storage
    external: false

networks:
  default:
    driver: bridge
    name: SpritNet-DevOps
